baseURL = 'https://architmanek.com/'
languageCode = 'en-us'
title = 'Archit Manek'
theme = "PaperMod"

[params]
  env = "production"
  homeInfoParams = { Title = "The Football Model", Content = "Reimagining football through data and machine learning." }

  # Social Icons
  socialIcons = [
    { name = "github", url = "https://github.com/archit-manek" },
    { name = "x", url = "https://x.com/archit_manek" }
  ]

  # Favicon Configuration
  [params.assets]
    favicon = "favicon-64x64.png"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    favicon48x48 = "favicon-48x48.png"
    favicon64x64 = "favicon-64x64.png"
    apple_touch_icon = "apple-touch-icon.png"


  # Giscus Comments Configuration
  [params.giscus]
    repo = "archit-manek/personal-blog"
    repoId = "R_kgDOPEo29g"
    category = "Announcements"
    categoryId = "DIC_kwDOPEo29s4CtKEW"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

  # Home page
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10
  identifier = "home"

  # Archive page
[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 30
  identifier = "archives"

  # Categories page
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 40
  identifier = "categories"

  # Tags page
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 50
  identifier = "tags"